export enum DispatchTypeEnum {
  SET_AVAILABLE_RECIPIENTS = 'SET_AVAILABLE_RECIPIENTS',
  ADD_RECIPIENT = 'ADD_RECIPIENT',
  REMOVE_RECIPIENT = 'REMOVE_RECIPIENT',
  CHANGE_EMAIL_SELECTION = 'CHANGE_EMAIL_SELECTION',
  SET_INVALID_EMAIL = 'SET_INVALID_EMAIL',
}
